### ISSUE TITLE
Unable to deserialize response content to Account.cs

### ISSUE THREAD

**Issue by raosaddam** [RileyGe/dotnet-algorand-sdk#9]
I'm trying to get account information using V2 api. I have cloned the repo so when I step inside I see I'm getting correct response but unable to deserialize response content to V2\Model\Account.cs. All the values are null.

<img width="1144" alt="Screen Shot 2020-11-09 at 11 46 40 PM" src="https://user-images.githubusercontent.com/16712886/98629063-0e241400-22e6-11eb-88c4-48853be6af81.png">
<img width="1151" alt="Screen Shot 2020-11-09 at 11 43 35 PM" src="https://user-images.githubusercontent.com/16712886/98629176-4a577480-22e6-11eb-93a0-060c2f95210d.png">

**Comment by RileyGe** [comment]
Can you please post the code you are using? If you using the sample writing by me, please tell me which one are you using.

**Comment by raosaddam** [comment]
Im running sdk-example project

![Capture_algod](https://user-images.githubusercontent.com/16712886/98698967-9cc77e00-2344-11eb-91d0-27d0c510eda8.PNG)

**Comment by raosaddam** [comment]
Also I noticed nuget package still doesn't have V2. Can you update that as well

**Comment by RileyGe** [comment]
The SDK v0.2 already including the API v2.

I noticed that you are using the purestake, it's the problem. I tried the example using a node(testnet), everything is OK. Sometimes weird behaviors occur when using purestake. Including but not limited to using API v2, it is better to use https://testnet-algorand.api.purestake.io/ps2 instead of https://testnet-algorand.api.purestake.io/ps1.
If you have no more questions, I will close this issue.
